[default.extend-words]
Websit = "Websit"
Hepler = "Hepler"
lso = "lso"
atual = "atual"
Linke = "Linke"
Cahe = "Cahe"
hight = "hight"
cros = "cros"
sistem = "sistem"
fileds = "fileds"
versionn = "versionn"
datas = "datas"
Visiable = "Visiable"
Rrror = "Rrror"
restauration = "restauration"
fonction = "fonction"
davantage = "davantage"
facilitant = "facilitant"
certificat = "certificat"
conteneurs = "conteneurs"
principales = "principales"
sur = "sur"
Cutom = "Cutom"
Datas = "Datas"
[files]
extend-exclude = [".github/workflows/tyops-check.yml", "docs/README.fr.md", "frontend/src/views/website/website/index.vue", "frontend/src/lang/modules/ru.ts", "frontend/src/views/setting/backup-account/operate/index.vue", "frontend/src/views/website/runtime/php/create/index.vue", "agent/utils/firewall/client/iptables.go", "agent/utils/firewall/client/firewalld.go", "agent/utils/firewall/client/ufw.go", "frontend/src/views/app-store/apps/index.vue", "frontend/src/views/container/container/monitor/index.vue", "frontend/src/views/ai/model/tensorrt/operate/index.vue", "frontend/src/views/ai/model/tensorrt/index.vue", "frontend/src/views/ai/mcp/server/index.vue", "frontend/src/views/host/monitor/monitor/index.vue"]
