[default.extend-words]
Websit = "Websit"
Hepler = "Hepler"
lso = "lso"
atual = "atual"
Linke = "Linke"
Cahe = "Cahe"
hight = "hight"
cros = "cros"
sistem = "sistem"
fileds = "fileds"
versionn = "versionn"
datas = "datas"
Visiable = "Visiable"
Rrror = "Rrror"
restauration = "restauration"
fonction = "fonction"
davantage = "davantage"
facilitant = "facilitant"
certificat = "certificat"
conteneurs = "conteneurs"
principales = "principales"
sur = "sur"
Cutom = "Cutom"
Datas = "Datas"
grup = "grup"
ein = "ein"
ist = "ist"
anormal = "anormal"
populer = "populer"
rige = "rige"
distribuye = "distribuye"
aplicable = "aplicable"
Historial = "Historial"
administrar = "administrar"
excede = "excede"
ser = "ser"
Limite = "Limite"
Oficial = "Oficial"
Tema = "Tema"
tema = "tema"
inicial = "inicial"
onnections = "onnections"
connnection = "connnection"
expirence = "expirence"
Exmaple = "Exmaple"
conetnt = "conetnt"
Padam = "Padam"
padam = "padam"
seret = "seret"
Argumen = "Argumen"
templat = "templat"
Templat = "Templat"
Blok = "Blok"
blok = "blok"
simbol = "simbol"
Atribut = "Atribut"
analisis = "analisis"
Analisis = "Analisis"
sintaks = "sintaks"
senario = "senario"
Faktor = "Faktor"
respons = "respons"
Respons = "Respons"
soket = "soket"
maka = "maka"

[files]
extend-exclude = [".github/workflows/tyops-check.yml", "docs/README.fr.md", "docs/README.de.md", "docs/README.id.md", "docs/README.es-es.md", "frontend/src/views/website/website/index.vue", "frontend/src/lang/modules/ru.ts", "frontend/src/lang/modules/pt-br.ts", "frontend/src/lang/modules/ja.ts", "frontend/src/lang/modules/en.ts", "frontend/src/lang/modules/ms.ts", "core/i18n/lang/tr.yaml", "frontend/src/views/setting/backup-account/operate/index.vue", "frontend/src/views/website/runtime/php/create/index.vue", "agent/utils/firewall/client/iptables.go", "agent/utils/firewall/client/firewalld.go", "agent/utils/firewall/client/ufw.go", "frontend/src/views/app-store/apps/index.vue", "frontend/src/views/container/container/monitor/index.vue", "frontend/src/views/ai/model/tensorrt/operate/index.vue", "frontend/src/views/ai/model/tensorrt/index.vue", "frontend/src/views/ai/mcp/server/index.vue", "frontend/src/views/host/monitor/monitor/index.vue", "frontend/src/views/website/website/config/basic/rewrite/custom/index.vue"]
