[default.extend-words]
sistem = "sistem"
Sistem = "Sistem"
Standart = "Standart"
parametre = "parametre"
Parametre = "Parametre"
adres = "adres"
Adres = "Adres"
buton = "buton"
Buton = "Buton"
anormal = "anormal"
Anormal = "Anormal"
Tema = "Tema"
tema = "tema"
Paket = "Paket"
paket = "paket"
Grup = "Grup"
Soket = "Soket"
soket = "soket"
nin = "nin"
cros = "cros"
hight = "hight"
Datas = "Datas"
Cutom = "Cutom"
Cahe = "Cahe"
ABD = "ABD"
Performans = "Performans"
performans = "performans"
Linke = "Linke"
Hepler = "Hepler"
Gir = "Gir"
Rrror = "Rrror"
servise = "servise"
davantage = "davantage"
facilitant = "facilitant"
certificat = "certificat"
conteneurs = "conteneurs"
principales = "principales"
sur = "sur"
populer = "populer"
styl = "styl"
anser = "anser"

[files]
extend-exclude = ["lang/**/*"]
Commando = "Commando"
processos = "processos"
Erro = "Erro"
programa = "programa"
ser = "ser"
Websit = "Websit"
atual = "atual"
Construtor = "Construtor"
erros = "erros"
Limite = "Limite"
limite = "limite"
Eles = "Eles"
ative = "ative"
excede = "excede"
conter = "conter"
Trasversal = "Trasversal"
caractere = "caractere"
cliente = "cliente"
Prestes = "Prestes"
caracteres = "caracteres"
controle = "controle"
nomes = "nomes"
operacional = "operacional"
problemas = "problemas"
confirme = "confirme"
conetnt = "conetnt"
Oficial = "Oficial"
inicial = "inicial"
lso = "lso"
imge = "imge"
Blok = "Blok"
onnections = "onnections"
connnection = "connnection"
expirence = "expirence"
Visiable = "Visiable"
Exmaple = "Exmaple"
reques = "reques"
fo = "fo"
Broswer = "Broswer"
entrys = "entrys"
fileds = "fileds"
versionn = "versionn"
