[default.extend-words]
datas = "datas"
entrys = "entrys"
librarys = "librarys"
recrete = "recrete"
Erro = "Erro"
atual = "atual"
anormal = "anormal"
Comando = "Comando"
ser = "ser"
limite = "limite"
comando = "comando"
internacional = "internacional"
erros = "erros"
Cliente = "Cliente"
Comandos = "Comandos"
caracteres = "caracteres"
grup = "grup"
Grup = "Grup"
sistem = "sistem"
Paket = "Paket"
Sistem = "Sistem"
Analisis = "Analisis"
faktor = "faktor"
requiere = "requiere"
Sycn = "Sycn"
Lable = "Lable"
lable = "lable"
detectaron = "detectaron"
coincidente = "coincidente"
producto = "producto"
utiliza = "utiliza"
cliente = "cliente"
factores = "factores"
umarshal = "umarshal"
requset = "requset"
Runing = "Runing"
abd = "abd"
Websit = "Websit"
Linke = "Linke"
configuracion = "configuracion"
inicial = "inicial"
contener = "contener"
hight = "hight"
montajes = "montajes"
ignora = "ignora"
directorios = "directorios"
protocolos = "protocolos"
conetnt = "conetnt"
curso = "curso"
termine = "termine"
instale = "instale"
cros = "cros"
ba = "ba"
onnections = "onnections"
connnection = "connnection"
unsupport = "unsupport"
expirence = "expirence"
Broswer = "Broswer"
Hepler = "Hepler"
Exmaple = "Exmaple"
Cahe = "Cahe"
contianer = "contianer"
fileds = "fileds"
reques = "reques"
versionn = "versionn"
fo = "fo"
Visiable = "Visiable"
Cutom = "Cutom"
Rrror = "Rrror"
lso = "lso"
anser = "anser"
Columnas = "Columnas"
tootip = "tootip"
styl = "styl"

[files]
extend-exclude = [
  "lang/**/*",
  "docs/**/*.md"
]
