[default.extend-words]
autor = "autor"
oficial = "oficial"
requiere = "requiere"
problemas = "problemas"
accesible = "accesible"
versiones = "versiones"
detectaron = "detectaron"
contener = "contener"
extensiones = "extensiones"
ser = "ser"
ignora = "ignora"
cliente = "cliente"
cahe = "cahe"
aprox = "aprox"
previos = "previos"
linke = "linke"
comando = "comando"
comandos = "comandos"
clientes = "clientes"
dependencias = "dependencias"
confirmas = "confirmas"
inicial = "inicial"
programas = "programas"
programa = "programa"
serie = "serie"
hight = "hight"
regiones = "regiones"
directorios = "directorios"
protocolos = "protocolos"
inmutable = "inmutable"
caracteres = "caracteres"
historial = "historial"
momento = "momento"
posible = "posible"
procede = "procede"
utiliza = "utiliza"
hace = "hace"
tema = "tema"
