
name: General PR Handling for 1Panel
on: pull_request
permissions:
  pull-requests: write
jobs:
  generic_handler:
    name: Add Labels to PR
    if: github.repository == '1Panel-dev/1Panel' && github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
      - uses: actions-ecosystem/action-add-labels@1a9c3715c0037e96b97bb38cb4c4b56a1f1d4871
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          labels: ${{ github.base_ref }}
