name: Build And Publish (OSS + R2)

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '24.11.1'

      - name: Build Web
        run: |
          cd frontend && npm install && npm run build:pro
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version: '1.25'
          cache-dependency-path: |
            core/go.sum
            agent/go.sum

      - name: Build Release
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --skip=publish --clean

      - name: Upload Assets
        uses: softprops/action-gh-release@26994186c0ac3ef5cae75ac16aa32e8153525f77
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/*.tar.gz
            dist/checksums.txt

      - name: Setup OSSUTIL
        uses: yizhoumo/setup-ossutil@80f4dc3682862e71bd1ccc10acc2328f8d00a11a
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          ossutil-version: '1.7.18'

      - name: Upload Assets to OSS
        run: |
          ossutil cp -r dist/ oss://resource-fit2cloud-com/1panel/package/v2/stable/${{ github.ref_name }}/release/ --include "*.tar.gz" --include "checksums.txt" --only-current-dir --force

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@02a3642a1ad72d5b765f48873141b9f26e9082f1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Upload to Cloudflare R2
        run: |
          rclone copy dist/ cloudflare_r2:package/v2/stable/${{ github.ref_name }}/release/ --include "*.tar.gz" --include "checksums.txt" --progress
