name: SonarCloud Scan
on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    if: github.repository == '1Panel-dev/1Panel'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ba3875ecf642b2129de2b589510c81a8b53dbf4e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}