name: Typos Check
on: pull_request
jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Check spelling
      uses: crate-ci/typos@f225da8c1e309bb995bf676bd8e1378370b4352a